FROM node:22-alpine AS build

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY client ./client
RUN npm run build:client

FROM nginx:alpine

COPY --from=build /usr/src/app/client/dist /usr/share/nginx/html
COPY client/nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
